#!/bin/bash

kubectl apply -f ./monitoring/namespace.yml
kubectl apply -f ./monitoring/common/
kubectl apply -f ./monitoring/kube-state-metrics/
kubectl apply -f ./monitoring/node-exporter/ --namespace monitoring
kubectl apply -f ./monitoring/prometheus/ --namespace monitoring
kubectl apply -f ./monitoring/grafana/ --namespace monitoring
